# Generated by Django 2.0 on 2018-03-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballrecord',
            name='id',
        ),
        migrations.RemoveField(
            model_name='batrecord',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fieldrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='ballrecord',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='players.Player'),
        ),
        migrations.AlterField(
            model_name='batrecord',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='players.Player'),
        ),
        migrations.AlterField(
            model_name='fieldrecord',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='players.Player'),
        ),
    ]
