# Generated by Django 2.0 on 2018-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20180310_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballrecord',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='batrecord',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldrecord',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
