# Generated by Django 2.0 on 2018-03-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20180313_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballrecord',
            name='match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batrecord',
            name='match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldrecord',
            name='match',
            field=models.IntegerField(default=0),
        ),
    ]
