# Generated by Django 2.0.3 on 2018-03-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20180310_0149'),
        ('scores', '0004_auto_20180314_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedRecord',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='players.Player')),
                ('match', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=2)),
            ],
        ),
    ]
