# Generated by Django 2.0 on 2018-03-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='id',
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='name',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='black_mamba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
