# Generated by Django 2.0 on 2018-03-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180308_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='substitutions',
        ),
    ]
