# Generated by Django 2.0 on 2018-03-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20180310_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
