# Generated by Django 2.0 on 2018-03-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20180310_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='playerteam',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
