# Generated by Django 2.0.3 on 2018-03-15 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('team', '0008_auto_20180314_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('match', models.CharField(default='1', max_length=3)),
            ],
        ),
    ]
