# Generated by Django 2.0 on 2018-03-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20180306_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('highest_run', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('run_conceded', models.IntegerField(default=0)),
                ('highest_wicket', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='capped',
        ),
        migrations.AddField(
            model_name='player',
            name='squad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='fresher_pg',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
